version: "3.9"
services:
  tor-flood-attack:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 16
      restart_policy:
        condition: any
        delay: 15s
        window: 60s
